// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: goods_stock.proto

package protoc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetGoodsStockRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodsID int64 `protobuf:"varint,1,opt,name=goodsID,proto3" json:"goodsID,omitempty"`
}

func (x *GetGoodsStockRequest) Reset() {
	*x = GetGoodsStockRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_stock_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGoodsStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoodsStockRequest) ProtoMessage() {}

func (x *GetGoodsStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goods_stock_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoodsStockRequest.ProtoReflect.Descriptor instead.
func (*GetGoodsStockRequest) Descriptor() ([]byte, []int) {
	return file_goods_stock_proto_rawDescGZIP(), []int{0}
}

func (x *GetGoodsStockRequest) GetGoodsID() int64 {
	if x != nil {
		return x.GoodsID
	}
	return 0
}

type GetGoodsStockResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	States    int64 `protobuf:"varint,1,opt,name=states,proto3" json:"states,omitempty"`
	GoodsNums int64 `protobuf:"varint,2,opt,name=goods_nums,json=goodsNums,proto3" json:"goods_nums,omitempty"`
}

func (x *GetGoodsStockResponse) Reset() {
	*x = GetGoodsStockResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_stock_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGoodsStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoodsStockResponse) ProtoMessage() {}

func (x *GetGoodsStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goods_stock_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoodsStockResponse.ProtoReflect.Descriptor instead.
func (*GetGoodsStockResponse) Descriptor() ([]byte, []int) {
	return file_goods_stock_proto_rawDescGZIP(), []int{1}
}

func (x *GetGoodsStockResponse) GetStates() int64 {
	if x != nil {
		return x.States
	}
	return 0
}

func (x *GetGoodsStockResponse) GetGoodsNums() int64 {
	if x != nil {
		return x.GoodsNums
	}
	return 0
}

var File_goods_stock_proto protoreflect.FileDescriptor

var file_goods_stock_proto_rawDesc = []byte{
	0x0a, 0x11, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x67, 0x6f, 0x6f, 0x64, 0x73,
	0x22, 0x30, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x53, 0x74, 0x6f, 0x63,
	0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x6f, 0x6f, 0x64,
	0x73, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x67, 0x6f, 0x6f, 0x64, 0x73,
	0x49, 0x44, 0x22, 0x4e, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x53, 0x74,
	0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x6e, 0x75, 0x6d,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x4e, 0x75,
	0x6d, 0x73, 0x32, 0x6a, 0x0a, 0x07, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x4f, 0x70, 0x12, 0x5f, 0x0a,
	0x16, 0x47, 0x65, 0x74, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x42, 0x79,
	0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x44, 0x12, 0x21, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f,
	0x67, 0x6f, 0x6f, 0x64, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x53, 0x74,
	0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x73, 0x74, 0x6f,
	0x63, 0x6b, 0x5f, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x6f, 0x6f, 0x64,
	0x73, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0a,
	0x5a, 0x08, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_goods_stock_proto_rawDescOnce sync.Once
	file_goods_stock_proto_rawDescData = file_goods_stock_proto_rawDesc
)

func file_goods_stock_proto_rawDescGZIP() []byte {
	file_goods_stock_proto_rawDescOnce.Do(func() {
		file_goods_stock_proto_rawDescData = protoimpl.X.CompressGZIP(file_goods_stock_proto_rawDescData)
	})
	return file_goods_stock_proto_rawDescData
}

var file_goods_stock_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_goods_stock_proto_goTypes = []interface{}{
	(*GetGoodsStockRequest)(nil),  // 0: stock_goods.GetGoodsStockRequest
	(*GetGoodsStockResponse)(nil), // 1: stock_goods.GetGoodsStockResponse
}
var file_goods_stock_proto_depIdxs = []int32{
	0, // 0: stock_goods.StockOp.GetGoodsStockByGoodsID:input_type -> stock_goods.GetGoodsStockRequest
	1, // 1: stock_goods.StockOp.GetGoodsStockByGoodsID:output_type -> stock_goods.GetGoodsStockResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_goods_stock_proto_init() }
func file_goods_stock_proto_init() {
	if File_goods_stock_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_goods_stock_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGoodsStockRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_stock_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGoodsStockResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_goods_stock_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_goods_stock_proto_goTypes,
		DependencyIndexes: file_goods_stock_proto_depIdxs,
		MessageInfos:      file_goods_stock_proto_msgTypes,
	}.Build()
	File_goods_stock_proto = out.File
	file_goods_stock_proto_rawDesc = nil
	file_goods_stock_proto_goTypes = nil
	file_goods_stock_proto_depIdxs = nil
}
