// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: stock_op.proto

package protoc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StockOpClient is the client API for StockOp service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StockOpClient interface {
	OrderReturn(ctx context.Context, in *OrderReturnRequest, opts ...grpc.CallOption) (*OrderReturnResponse, error)
	SupplierIncrease(ctx context.Context, in *SupplierIncreaseRequest, opts ...grpc.CallOption) (*SupplierIncreaseResponse, error)
	SupplierReduce(ctx context.Context, in *SupplierReduceRequest, opts ...grpc.CallOption) (*SupplierReduceResponse, error)
	GetGoodsStockByGoodsIDList(ctx context.Context, in *GetGoodsStockRequest, opts ...grpc.CallOption) (*GetGoodsStockResponse, error)
}

type stockOpClient struct {
	cc grpc.ClientConnInterface
}

func NewStockOpClient(cc grpc.ClientConnInterface) StockOpClient {
	return &stockOpClient{cc}
}

func (c *stockOpClient) OrderReturn(ctx context.Context, in *OrderReturnRequest, opts ...grpc.CallOption) (*OrderReturnResponse, error) {
	out := new(OrderReturnResponse)
	err := c.cc.Invoke(ctx, "/stock_op.StockOp/OrderReturn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockOpClient) SupplierIncrease(ctx context.Context, in *SupplierIncreaseRequest, opts ...grpc.CallOption) (*SupplierIncreaseResponse, error) {
	out := new(SupplierIncreaseResponse)
	err := c.cc.Invoke(ctx, "/stock_op.StockOp/SupplierIncrease", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockOpClient) SupplierReduce(ctx context.Context, in *SupplierReduceRequest, opts ...grpc.CallOption) (*SupplierReduceResponse, error) {
	out := new(SupplierReduceResponse)
	err := c.cc.Invoke(ctx, "/stock_op.StockOp/SupplierReduce", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockOpClient) GetGoodsStockByGoodsIDList(ctx context.Context, in *GetGoodsStockRequest, opts ...grpc.CallOption) (*GetGoodsStockResponse, error) {
	out := new(GetGoodsStockResponse)
	err := c.cc.Invoke(ctx, "/stock_op.StockOp/GetGoodsStockByGoodsIDList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StockOpServer is the server API for StockOp service.
// All implementations must embed UnimplementedStockOpServer
// for forward compatibility
type StockOpServer interface {
	OrderReturn(context.Context, *OrderReturnRequest) (*OrderReturnResponse, error)
	SupplierIncrease(context.Context, *SupplierIncreaseRequest) (*SupplierIncreaseResponse, error)
	SupplierReduce(context.Context, *SupplierReduceRequest) (*SupplierReduceResponse, error)
	GetGoodsStockByGoodsIDList(context.Context, *GetGoodsStockRequest) (*GetGoodsStockResponse, error)
	mustEmbedUnimplementedStockOpServer()
}

// UnimplementedStockOpServer must be embedded to have forward compatible implementations.
type UnimplementedStockOpServer struct {
}

func (UnimplementedStockOpServer) OrderReturn(context.Context, *OrderReturnRequest) (*OrderReturnResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OrderReturn not implemented")
}
func (UnimplementedStockOpServer) SupplierIncrease(context.Context, *SupplierIncreaseRequest) (*SupplierIncreaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SupplierIncrease not implemented")
}
func (UnimplementedStockOpServer) SupplierReduce(context.Context, *SupplierReduceRequest) (*SupplierReduceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SupplierReduce not implemented")
}
func (UnimplementedStockOpServer) GetGoodsStockByGoodsIDList(context.Context, *GetGoodsStockRequest) (*GetGoodsStockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGoodsStockByGoodsIDList not implemented")
}
func (UnimplementedStockOpServer) mustEmbedUnimplementedStockOpServer() {}

// UnsafeStockOpServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StockOpServer will
// result in compilation errors.
type UnsafeStockOpServer interface {
	mustEmbedUnimplementedStockOpServer()
}

func RegisterStockOpServer(s grpc.ServiceRegistrar, srv StockOpServer) {
	s.RegisterService(&StockOp_ServiceDesc, srv)
}

func _StockOp_OrderReturn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderReturnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockOpServer).OrderReturn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stock_op.StockOp/OrderReturn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockOpServer).OrderReturn(ctx, req.(*OrderReturnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StockOp_SupplierIncrease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SupplierIncreaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockOpServer).SupplierIncrease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stock_op.StockOp/SupplierIncrease",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockOpServer).SupplierIncrease(ctx, req.(*SupplierIncreaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StockOp_SupplierReduce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SupplierReduceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockOpServer).SupplierReduce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stock_op.StockOp/SupplierReduce",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockOpServer).SupplierReduce(ctx, req.(*SupplierReduceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StockOp_GetGoodsStockByGoodsIDList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGoodsStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockOpServer).GetGoodsStockByGoodsIDList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stock_op.StockOp/GetGoodsStockByGoodsIDList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockOpServer).GetGoodsStockByGoodsIDList(ctx, req.(*GetGoodsStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StockOp_ServiceDesc is the grpc.ServiceDesc for StockOp service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StockOp_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stock_op.StockOp",
	HandlerType: (*StockOpServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OrderReturn",
			Handler:    _StockOp_OrderReturn_Handler,
		},
		{
			MethodName: "SupplierIncrease",
			Handler:    _StockOp_SupplierIncrease_Handler,
		},
		{
			MethodName: "SupplierReduce",
			Handler:    _StockOp_SupplierReduce_Handler,
		},
		{
			MethodName: "GetGoodsStockByGoodsIDList",
			Handler:    _StockOp_GetGoodsStockByGoodsIDList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stock_op.proto",
}
