// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: stock_goods.proto

package protoc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GetGoodsStockClient is the client API for GetGoodsStock service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GetGoodsStockClient interface {
	GetGoodsStockByGoodsID(ctx context.Context, in *GetGoodsStockRequest, opts ...grpc.CallOption) (*GetGoodsStockResponse, error)
}

type getGoodsStockClient struct {
	cc grpc.ClientConnInterface
}

func NewGetGoodsStockClient(cc grpc.ClientConnInterface) GetGoodsStockClient {
	return &getGoodsStockClient{cc}
}

func (c *getGoodsStockClient) GetGoodsStockByGoodsID(ctx context.Context, in *GetGoodsStockRequest, opts ...grpc.CallOption) (*GetGoodsStockResponse, error) {
	out := new(GetGoodsStockResponse)
	err := c.cc.Invoke(ctx, "/stock_goods.GetGoodsStock/GetGoodsStockByGoodsID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetGoodsStockServer is the server API for GetGoodsStock service.
// All implementations must embed UnimplementedGetGoodsStockServer
// for forward compatibility
type GetGoodsStockServer interface {
	GetGoodsStockByGoodsID(context.Context, *GetGoodsStockRequest) (*GetGoodsStockResponse, error)
	mustEmbedUnimplementedGetGoodsStockServer()
}

// UnimplementedGetGoodsStockServer must be embedded to have forward compatible implementations.
type UnimplementedGetGoodsStockServer struct {
}

func (UnimplementedGetGoodsStockServer) GetGoodsStockByGoodsID(context.Context, *GetGoodsStockRequest) (*GetGoodsStockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGoodsStockByGoodsID not implemented")
}
func (UnimplementedGetGoodsStockServer) mustEmbedUnimplementedGetGoodsStockServer() {}

// UnsafeGetGoodsStockServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetGoodsStockServer will
// result in compilation errors.
type UnsafeGetGoodsStockServer interface {
	mustEmbedUnimplementedGetGoodsStockServer()
}

func RegisterGetGoodsStockServer(s grpc.ServiceRegistrar, srv GetGoodsStockServer) {
	s.RegisterService(&GetGoodsStock_ServiceDesc, srv)
}

func _GetGoodsStock_GetGoodsStockByGoodsID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGoodsStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetGoodsStockServer).GetGoodsStockByGoodsID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stock_goods.GetGoodsStock/GetGoodsStockByGoodsID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetGoodsStockServer).GetGoodsStockByGoodsID(ctx, req.(*GetGoodsStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GetGoodsStock_ServiceDesc is the grpc.ServiceDesc for GetGoodsStock service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetGoodsStock_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stock_goods.GetGoodsStock",
	HandlerType: (*GetGoodsStockServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGoodsStockByGoodsID",
			Handler:    _GetGoodsStock_GetGoodsStockByGoodsID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stock_goods.proto",
}
