// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: stock_op.proto

package protoc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StockOpGoodInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodsId int64 `protobuf:"varint,1,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
	Num     int64 `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *StockOpGoodInfo) Reset() {
	*x = StockOpGoodInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stock_op_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StockOpGoodInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockOpGoodInfo) ProtoMessage() {}

func (x *StockOpGoodInfo) ProtoReflect() protoreflect.Message {
	mi := &file_stock_op_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockOpGoodInfo.ProtoReflect.Descriptor instead.
func (*StockOpGoodInfo) Descriptor() ([]byte, []int) {
	return file_stock_op_proto_rawDescGZIP(), []int{0}
}

func (x *StockOpGoodInfo) GetGoodsId() int64 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *StockOpGoodInfo) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

type OrderReturnRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodsInfo []*StockOpGoodInfo `protobuf:"bytes,1,rep,name=goodsInfo,proto3" json:"goodsInfo,omitempty"`
	OrderID   int64              `protobuf:"varint,2,opt,name=orderID,proto3" json:"orderID,omitempty"`
}

func (x *OrderReturnRequest) Reset() {
	*x = OrderReturnRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stock_op_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderReturnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderReturnRequest) ProtoMessage() {}

func (x *OrderReturnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stock_op_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderReturnRequest.ProtoReflect.Descriptor instead.
func (*OrderReturnRequest) Descriptor() ([]byte, []int) {
	return file_stock_op_proto_rawDescGZIP(), []int{1}
}

func (x *OrderReturnRequest) GetGoodsInfo() []*StockOpGoodInfo {
	if x != nil {
		return x.GoodsInfo
	}
	return nil
}

func (x *OrderReturnRequest) GetOrderID() int64 {
	if x != nil {
		return x.OrderID
	}
	return 0
}

type OrderReturnResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	States int64 `protobuf:"varint,1,opt,name=states,proto3" json:"states,omitempty"`
}

func (x *OrderReturnResponse) Reset() {
	*x = OrderReturnResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stock_op_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderReturnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderReturnResponse) ProtoMessage() {}

func (x *OrderReturnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stock_op_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderReturnResponse.ProtoReflect.Descriptor instead.
func (*OrderReturnResponse) Descriptor() ([]byte, []int) {
	return file_stock_op_proto_rawDescGZIP(), []int{2}
}

func (x *OrderReturnResponse) GetStates() int64 {
	if x != nil {
		return x.States
	}
	return 0
}

type SupplierIncreaseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodsInfo  []*StockOpGoodInfo `protobuf:"bytes,1,rep,name=goodsInfo,proto3" json:"goodsInfo,omitempty"`
	SupplierID int64              `protobuf:"varint,2,opt,name=supplierID,proto3" json:"supplierID,omitempty"`
}

func (x *SupplierIncreaseRequest) Reset() {
	*x = SupplierIncreaseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stock_op_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SupplierIncreaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupplierIncreaseRequest) ProtoMessage() {}

func (x *SupplierIncreaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stock_op_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupplierIncreaseRequest.ProtoReflect.Descriptor instead.
func (*SupplierIncreaseRequest) Descriptor() ([]byte, []int) {
	return file_stock_op_proto_rawDescGZIP(), []int{3}
}

func (x *SupplierIncreaseRequest) GetGoodsInfo() []*StockOpGoodInfo {
	if x != nil {
		return x.GoodsInfo
	}
	return nil
}

func (x *SupplierIncreaseRequest) GetSupplierID() int64 {
	if x != nil {
		return x.SupplierID
	}
	return 0
}

type SupplierIncreaseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	States int64 `protobuf:"varint,1,opt,name=states,proto3" json:"states,omitempty"`
}

func (x *SupplierIncreaseResponse) Reset() {
	*x = SupplierIncreaseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stock_op_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SupplierIncreaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupplierIncreaseResponse) ProtoMessage() {}

func (x *SupplierIncreaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stock_op_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupplierIncreaseResponse.ProtoReflect.Descriptor instead.
func (*SupplierIncreaseResponse) Descriptor() ([]byte, []int) {
	return file_stock_op_proto_rawDescGZIP(), []int{4}
}

func (x *SupplierIncreaseResponse) GetStates() int64 {
	if x != nil {
		return x.States
	}
	return 0
}

type SupplierReduceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodsInfo  []*StockOpGoodInfo `protobuf:"bytes,1,rep,name=goodsInfo,proto3" json:"goodsInfo,omitempty"`
	SupplierID int64              `protobuf:"varint,2,opt,name=supplierID,proto3" json:"supplierID,omitempty"`
}

func (x *SupplierReduceRequest) Reset() {
	*x = SupplierReduceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stock_op_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SupplierReduceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupplierReduceRequest) ProtoMessage() {}

func (x *SupplierReduceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stock_op_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupplierReduceRequest.ProtoReflect.Descriptor instead.
func (*SupplierReduceRequest) Descriptor() ([]byte, []int) {
	return file_stock_op_proto_rawDescGZIP(), []int{5}
}

func (x *SupplierReduceRequest) GetGoodsInfo() []*StockOpGoodInfo {
	if x != nil {
		return x.GoodsInfo
	}
	return nil
}

func (x *SupplierReduceRequest) GetSupplierID() int64 {
	if x != nil {
		return x.SupplierID
	}
	return 0
}

type SupplierReduceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	States int64 `protobuf:"varint,1,opt,name=states,proto3" json:"states,omitempty"`
}

func (x *SupplierReduceResponse) Reset() {
	*x = SupplierReduceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stock_op_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SupplierReduceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupplierReduceResponse) ProtoMessage() {}

func (x *SupplierReduceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stock_op_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupplierReduceResponse.ProtoReflect.Descriptor instead.
func (*SupplierReduceResponse) Descriptor() ([]byte, []int) {
	return file_stock_op_proto_rawDescGZIP(), []int{6}
}

func (x *SupplierReduceResponse) GetStates() int64 {
	if x != nil {
		return x.States
	}
	return 0
}

type StockOpGoodsID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodsId int64 `protobuf:"varint,1,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
}

func (x *StockOpGoodsID) Reset() {
	*x = StockOpGoodsID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stock_op_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StockOpGoodsID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockOpGoodsID) ProtoMessage() {}

func (x *StockOpGoodsID) ProtoReflect() protoreflect.Message {
	mi := &file_stock_op_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockOpGoodsID.ProtoReflect.Descriptor instead.
func (*StockOpGoodsID) Descriptor() ([]byte, []int) {
	return file_stock_op_proto_rawDescGZIP(), []int{7}
}

func (x *StockOpGoodsID) GetGoodsId() int64 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

type StockGoodsData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodsId  int64 `protobuf:"varint,1,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
	GoodsNum int64 `protobuf:"varint,2,opt,name=goods_num,json=goodsNum,proto3" json:"goods_num,omitempty"`
}

func (x *StockGoodsData) Reset() {
	*x = StockGoodsData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stock_op_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StockGoodsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockGoodsData) ProtoMessage() {}

func (x *StockGoodsData) ProtoReflect() protoreflect.Message {
	mi := &file_stock_op_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockGoodsData.ProtoReflect.Descriptor instead.
func (*StockGoodsData) Descriptor() ([]byte, []int) {
	return file_stock_op_proto_rawDescGZIP(), []int{8}
}

func (x *StockGoodsData) GetGoodsId() int64 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *StockGoodsData) GetGoodsNum() int64 {
	if x != nil {
		return x.GoodsNum
	}
	return 0
}

type GetGoodsStockRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodsID []*StockOpGoodsID `protobuf:"bytes,1,rep,name=goodsID,proto3" json:"goodsID,omitempty"`
}

func (x *GetGoodsStockRequest) Reset() {
	*x = GetGoodsStockRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stock_op_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGoodsStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoodsStockRequest) ProtoMessage() {}

func (x *GetGoodsStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stock_op_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoodsStockRequest.ProtoReflect.Descriptor instead.
func (*GetGoodsStockRequest) Descriptor() ([]byte, []int) {
	return file_stock_op_proto_rawDescGZIP(), []int{9}
}

func (x *GetGoodsStockRequest) GetGoodsID() []*StockOpGoodsID {
	if x != nil {
		return x.GoodsID
	}
	return nil
}

type GetGoodsStockResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	States     int64             `protobuf:"varint,1,opt,name=states,proto3" json:"states,omitempty"`
	GoodsStock []*StockGoodsData `protobuf:"bytes,2,rep,name=GoodsStock,proto3" json:"GoodsStock,omitempty"`
}

func (x *GetGoodsStockResponse) Reset() {
	*x = GetGoodsStockResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stock_op_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGoodsStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoodsStockResponse) ProtoMessage() {}

func (x *GetGoodsStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stock_op_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoodsStockResponse.ProtoReflect.Descriptor instead.
func (*GetGoodsStockResponse) Descriptor() ([]byte, []int) {
	return file_stock_op_proto_rawDescGZIP(), []int{10}
}

func (x *GetGoodsStockResponse) GetStates() int64 {
	if x != nil {
		return x.States
	}
	return 0
}

func (x *GetGoodsStockResponse) GetGoodsStock() []*StockGoodsData {
	if x != nil {
		return x.GoodsStock
	}
	return nil
}

var File_stock_op_proto protoreflect.FileDescriptor

var file_stock_op_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x6f, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x6f, 0x70, 0x22, 0x3e, 0x0a, 0x0f, 0x53, 0x74,
	0x6f, 0x63, 0x6b, 0x4f, 0x70, 0x47, 0x6f, 0x6f, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x19, 0x0a,
	0x08, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22, 0x67, 0x0a, 0x12, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x37, 0x0a, 0x09, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x6f, 0x70, 0x2e, 0x53,
	0x74, 0x6f, 0x63, 0x6b, 0x4f, 0x70, 0x47, 0x6f, 0x6f, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09,
	0x67, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x49, 0x44, 0x22, 0x2d, 0x0a, 0x13, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x74, 0x75,
	0x72, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x73, 0x22, 0x72, 0x0a, 0x17, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x49, 0x6e,
	0x63, 0x72, 0x65, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x37, 0x0a,
	0x09, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x6f, 0x70, 0x2e, 0x53, 0x74, 0x6f, 0x63,
	0x6b, 0x4f, 0x70, 0x47, 0x6f, 0x6f, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x67, 0x6f, 0x6f,
	0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x69,
	0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x73, 0x75, 0x70, 0x70,
	0x6c, 0x69, 0x65, 0x72, 0x49, 0x44, 0x22, 0x32, 0x0a, 0x18, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x69,
	0x65, 0x72, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x65, 0x73, 0x22, 0x70, 0x0a, 0x15, 0x53, 0x75,
	0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x37, 0x0a, 0x09, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x6f,
	0x70, 0x2e, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x4f, 0x70, 0x47, 0x6f, 0x6f, 0x64, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x09, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1e, 0x0a, 0x0a,
	0x73, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0a, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x49, 0x44, 0x22, 0x30, 0x0a, 0x16,
	0x53, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x65, 0x73, 0x22, 0x2b,
	0x0a, 0x0e, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x4f, 0x70, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x44,
	0x12, 0x19, 0x0a, 0x08, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x64, 0x22, 0x48, 0x0a, 0x0e, 0x53,
	0x74, 0x6f, 0x63, 0x6b, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x44, 0x61, 0x74, 0x61, 0x12, 0x19, 0x0a,
	0x08, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x67, 0x6f, 0x6f, 0x64,
	0x73, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x67, 0x6f, 0x6f,
	0x64, 0x73, 0x4e, 0x75, 0x6d, 0x22, 0x4a, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x47, 0x6f, 0x6f, 0x64,
	0x73, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x32, 0x0a,
	0x07, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x44, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x6f, 0x70, 0x2e, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x4f,
	0x70, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x44, 0x52, 0x07, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x49,
	0x44, 0x22, 0x69, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x53, 0x74, 0x6f,
	0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x73, 0x12, 0x38, 0x0a, 0x0a, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x53, 0x74, 0x6f, 0x63, 0x6b,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x6f,
	0x70, 0x2e, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x0a, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x32, 0xe4, 0x02, 0x0a,
	0x07, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x4f, 0x70, 0x12, 0x4a, 0x0a, 0x0b, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x12, 0x1c, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f,
	0x6f, 0x70, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x6f, 0x70,
	0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x59, 0x0a, 0x10, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72,
	0x49, 0x6e, 0x63, 0x72, 0x65, 0x61, 0x73, 0x65, 0x12, 0x21, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b,
	0x5f, 0x6f, 0x70, 0x2e, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x49, 0x6e, 0x63, 0x72,
	0x65, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x73, 0x74,
	0x6f, 0x63, 0x6b, 0x5f, 0x6f, 0x70, 0x2e, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x49,
	0x6e, 0x63, 0x72, 0x65, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x53, 0x0a, 0x0e, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x52, 0x65, 0x64, 0x75, 0x63,
	0x65, 0x12, 0x1f, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x6f, 0x70, 0x2e, 0x53, 0x75, 0x70,
	0x70, 0x6c, 0x69, 0x65, 0x72, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x20, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x6f, 0x70, 0x2e, 0x53, 0x75,
	0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5d, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x47, 0x6f, 0x6f, 0x64, 0x73,
	0x53, 0x74, 0x6f, 0x63, 0x6b, 0x42, 0x79, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x44, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x1e, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x6f, 0x70, 0x2e, 0x47, 0x65,
	0x74, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x6f, 0x70, 0x2e, 0x47, 0x65,
	0x74, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_stock_op_proto_rawDescOnce sync.Once
	file_stock_op_proto_rawDescData = file_stock_op_proto_rawDesc
)

func file_stock_op_proto_rawDescGZIP() []byte {
	file_stock_op_proto_rawDescOnce.Do(func() {
		file_stock_op_proto_rawDescData = protoimpl.X.CompressGZIP(file_stock_op_proto_rawDescData)
	})
	return file_stock_op_proto_rawDescData
}

var file_stock_op_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_stock_op_proto_goTypes = []interface{}{
	(*StockOpGoodInfo)(nil),          // 0: stock_op.StockOpGoodInfo
	(*OrderReturnRequest)(nil),       // 1: stock_op.OrderReturnRequest
	(*OrderReturnResponse)(nil),      // 2: stock_op.OrderReturnResponse
	(*SupplierIncreaseRequest)(nil),  // 3: stock_op.SupplierIncreaseRequest
	(*SupplierIncreaseResponse)(nil), // 4: stock_op.SupplierIncreaseResponse
	(*SupplierReduceRequest)(nil),    // 5: stock_op.SupplierReduceRequest
	(*SupplierReduceResponse)(nil),   // 6: stock_op.SupplierReduceResponse
	(*StockOpGoodsID)(nil),           // 7: stock_op.StockOpGoodsID
	(*StockGoodsData)(nil),           // 8: stock_op.StockGoodsData
	(*GetGoodsStockRequest)(nil),     // 9: stock_op.GetGoodsStockRequest
	(*GetGoodsStockResponse)(nil),    // 10: stock_op.GetGoodsStockResponse
}
var file_stock_op_proto_depIdxs = []int32{
	0,  // 0: stock_op.OrderReturnRequest.goodsInfo:type_name -> stock_op.StockOpGoodInfo
	0,  // 1: stock_op.SupplierIncreaseRequest.goodsInfo:type_name -> stock_op.StockOpGoodInfo
	0,  // 2: stock_op.SupplierReduceRequest.goodsInfo:type_name -> stock_op.StockOpGoodInfo
	7,  // 3: stock_op.GetGoodsStockRequest.goodsID:type_name -> stock_op.StockOpGoodsID
	8,  // 4: stock_op.GetGoodsStockResponse.GoodsStock:type_name -> stock_op.StockGoodsData
	1,  // 5: stock_op.StockOp.OrderReturn:input_type -> stock_op.OrderReturnRequest
	3,  // 6: stock_op.StockOp.SupplierIncrease:input_type -> stock_op.SupplierIncreaseRequest
	5,  // 7: stock_op.StockOp.SupplierReduce:input_type -> stock_op.SupplierReduceRequest
	9,  // 8: stock_op.StockOp.GetGoodsStockByGoodsIDList:input_type -> stock_op.GetGoodsStockRequest
	2,  // 9: stock_op.StockOp.OrderReturn:output_type -> stock_op.OrderReturnResponse
	4,  // 10: stock_op.StockOp.SupplierIncrease:output_type -> stock_op.SupplierIncreaseResponse
	6,  // 11: stock_op.StockOp.SupplierReduce:output_type -> stock_op.SupplierReduceResponse
	10, // 12: stock_op.StockOp.GetGoodsStockByGoodsIDList:output_type -> stock_op.GetGoodsStockResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_stock_op_proto_init() }
func file_stock_op_proto_init() {
	if File_stock_op_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_stock_op_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StockOpGoodInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stock_op_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderReturnRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stock_op_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderReturnResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stock_op_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SupplierIncreaseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stock_op_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SupplierIncreaseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stock_op_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SupplierReduceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stock_op_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SupplierReduceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stock_op_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StockOpGoodsID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stock_op_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StockGoodsData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stock_op_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGoodsStockRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stock_op_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGoodsStockResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_stock_op_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stock_op_proto_goTypes,
		DependencyIndexes: file_stock_op_proto_depIdxs,
		MessageInfos:      file_stock_op_proto_msgTypes,
	}.Build()
	File_stock_op_proto = out.File
	file_stock_op_proto_rawDesc = nil
	file_stock_op_proto_goTypes = nil
	file_stock_op_proto_depIdxs = nil
}
