// Code generated by goctl. DO NOT EDIT!
// Source: stock_op.proto

package server

import (
	"context"

	"github.com/reation/micro_service_stock_service/protoc"
	"github.com/reation/micro_service_stock_service/stock_op/internal/logic"
	"github.com/reation/micro_service_stock_service/stock_op/internal/svc"
)

type StockOpServer struct {
	svcCtx *svc.ServiceContext
	protoc.UnimplementedStockOpServer
}

func NewStockOpServer(svcCtx *svc.ServiceContext) *StockOpServer {
	return &StockOpServer{
		svcCtx: svcCtx,
	}
}

func (s *StockOpServer) OrderReturn(ctx context.Context, in *protoc.OrderReturnRequest) (*protoc.OrderReturnResponse, error) {
	l := logic.NewOrderReturnLogic(ctx, s.svcCtx)
	return l.OrderReturn(in)
}

func (s *StockOpServer) SupplierIncrease(ctx context.Context, in *protoc.SupplierIncreaseRequest) (*protoc.SupplierIncreaseResponse, error) {
	l := logic.NewSupplierIncreaseLogic(ctx, s.svcCtx)
	return l.SupplierIncrease(in)
}

func (s *StockOpServer) SupplierReduce(ctx context.Context, in *protoc.SupplierReduceRequest) (*protoc.SupplierReduceResponse, error) {
	l := logic.NewSupplierReduceLogic(ctx, s.svcCtx)
	return l.SupplierReduce(in)
}

func (s *StockOpServer) GetGoodsStockByGoodsIDList(ctx context.Context, in *protoc.GetGoodsStockRequest) (*protoc.GetGoodsStockResponse, error) {
	l := logic.NewGetGoodsStockByGoodsIDListLogic(ctx, s.svcCtx)
	return l.GetGoodsStockByGoodsIDList(in)
}
