// Code generated by goctl. DO NOT EDIT!
// Source: stock_goods.proto

package server

import (
	"context"

	"github.com/reation/micro_service_stock_service/get_goods_stock_list/internal/logic"
	"github.com/reation/micro_service_stock_service/get_goods_stock_list/internal/svc"
	"github.com/reation/micro_service_stock_service/protoc"
)

type StockOpServer struct {
	svcCtx *svc.ServiceContext
	protoc.UnimplementedStockOpServer
}

func NewStockOpServer(svcCtx *svc.ServiceContext) *StockOpServer {
	return &StockOpServer{
		svcCtx: svcCtx,
	}
}

func (s *StockOpServer) GetGoodsStockByGoodsIDList(ctx context.Context, in *protoc.GetGoodsStockRequest) (*protoc.GetGoodsStockResponse, error) {
	l := logic.NewGetGoodsStockByGoodsIDListLogic(ctx, s.svcCtx)
	return l.GetGoodsStockByGoodsIDList(in)
}
