// Code generated by goctl. DO NOT EDIT.
// Source: stock.proto

package orderreducestockoperation

import (
	"context"

	"github.com/reation/micro_service_stock_service/protoc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	OrderGoodsID             = protoc.OrderGoodsID
	OrderReduceStockRequest  = protoc.OrderReduceStockRequest
	OrderReduceStockResponse = protoc.OrderReduceStockResponse
	OrderReturn              = protoc.OrderReturn

	OrderReduceStockOperation interface {
		OrderReduceStock(ctx context.Context, in *OrderReduceStockRequest, opts ...grpc.CallOption) (*OrderReduceStockResponse, error)
	}

	defaultOrderReduceStockOperation struct {
		cli zrpc.Client
	}
)

func NewOrderReduceStockOperation(cli zrpc.Client) OrderReduceStockOperation {
	return &defaultOrderReduceStockOperation{
		cli: cli,
	}
}

func (m *defaultOrderReduceStockOperation) OrderReduceStock(ctx context.Context, in *OrderReduceStockRequest, opts ...grpc.CallOption) (*OrderReduceStockResponse, error) {
	client := protoc.NewOrderReduceStockOperationClient(m.cli.Conn())
	return client.OrderReduceStock(ctx, in, opts...)
}
