// Code generated by goctl. DO NOT EDIT!
// Source: stock_goods.proto

package server

import (
	"context"

	"github.com/reation/micro_service_stock_service/goods_stock/internal/logic"
	"github.com/reation/micro_service_stock_service/goods_stock/internal/svc"
	"github.com/reation/micro_service_stock_service/protoc"
)

type GetGoodsStockServer struct {
	svcCtx *svc.ServiceContext
	protoc.UnimplementedGetGoodsStockServer
}

func NewGetGoodsStockServer(svcCtx *svc.ServiceContext) *GetGoodsStockServer {
	return &GetGoodsStockServer{
		svcCtx: svcCtx,
	}
}

func (s *GetGoodsStockServer) GetGoodsStockByGoodsID(ctx context.Context, in *protoc.GetGoodsStockRequest) (*protoc.GetGoodsStockResponse, error) {
	l := logic.NewGetGoodsStockByGoodsIDLogic(ctx, s.svcCtx)
	return l.GetGoodsStockByGoodsID(in)
}
