package config

var (
	GOODS_STOCK_STATE_NORMAL int64 = 1
	GOODS_STOCK_STATE_EMPTY  int64 = 21
	GOODS_STOCK_STATE_ERROR  int64 = 31

	ORDER_REDUCE_GOODS_TYPE_NORMAL int64 = 1
	ORDER_REDUCE_GOODS_TYPE_LESS   int64 = 21
	ORDER_REDUCE_GOODS_TYPE_ERRO   int64 = 51

	ORDER_REDUCE_STATES_NORMAL      int64 = 1
	ORDER_REDUCE_STATES_LESS        int64 = 21
	ORDER_REDUCE_STATES_ERROR       int64 = 31
	ORDER_INCREASE_STATES_NORMAL    int64 = 1
	ORDER_INCREASE_STATES_ERROR     int64 = 31
	SUPPLIER_INCREASE_STATES_NORMAL int64 = 1
	SUPPLIER_INCREASE_STATES_ERROR  int64 = 31
	IS_ALL_YES                      int64 = 1
	IS_ALL_NO                       int64 = 0

	ORDER_STATES_GOODS_SELECT_NORMAL int64 = 1
	ORDER_STATES_GOODS_SELECT_LESS   int64 = 21
	ORDER_STATES_GOODS_SELECT_ERROR  int64 = 31

	STOCK_OPERATION_TYPE_REDUCE   int64 = 0
	STOCK_OPERATION_TYPE_INCREASE int64 = 1

	TYPE_ORDER_REDUCE      int64 = 1
	TYPE_ORDER_INCREASE    int64 = 2
	TYPE_SUPPLIER_INCREASE int64 = 3
	TYPE_SUPPLIER_REDUCE   int64 = 4
)
