// Code generated by goctl. DO NOT EDIT.
// Source: stock.proto

package server

import (
	"context"

	"github.com/reation/micro_service_stock_service/order_reduce_stock/internal/logic"
	"github.com/reation/micro_service_stock_service/order_reduce_stock/internal/svc"
	"github.com/reation/micro_service_stock_service/protoc"
)

type OrderReduceStockOperationServer struct {
	svcCtx *svc.ServiceContext
	protoc.UnimplementedOrderReduceStockOperationServer
}

func NewOrderReduceStockOperationServer(svcCtx *svc.ServiceContext) *OrderReduceStockOperationServer {
	return &OrderReduceStockOperationServer{
		svcCtx: svcCtx,
	}
}

func (s *OrderReduceStockOperationServer) OrderReduceStock(ctx context.Context, in *protoc.OrderReduceStockRequest) (*protoc.OrderReduceStockResponse, error) {
	l := logic.NewOrderReduceStockLogic(ctx, s.svcCtx)
	return l.OrderReduceStock(in)
}
