// Code generated by goctl. DO NOT EDIT!
// Source: stock_goods.proto

package getgoodsstock

import (
	"context"

	"github.com/reation/micro_service_stock_service/protoc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetGoodsStockRequest  = protoc.GetGoodsStockRequest
	GetGoodsStockResponse = protoc.GetGoodsStockResponse

	GetGoodsStock interface {
		GetGoodsStockByGoodsID(ctx context.Context, in *GetGoodsStockRequest, opts ...grpc.CallOption) (*GetGoodsStockResponse, error)
	}

	defaultGetGoodsStock struct {
		cli zrpc.Client
	}
)

func NewGetGoodsStock(cli zrpc.Client) GetGoodsStock {
	return &defaultGetGoodsStock{
		cli: cli,
	}
}

func (m *defaultGetGoodsStock) GetGoodsStockByGoodsID(ctx context.Context, in *GetGoodsStockRequest, opts ...grpc.CallOption) (*GetGoodsStockResponse, error) {
	client := protoc.NewGetGoodsStockClient(m.cli.Conn())
	return client.GetGoodsStockByGoodsID(ctx, in, opts...)
}
